<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ вакансий из HeadHunter

In [3]:
import pandas as pd
import psycopg2

In [5]:
connection = psycopg2.connect(
    dbname=DBNAME,
    user=USER,
    host=HOST,
    password=PASSWORD,
    port=PORT
)

# Юнит 3. Предварительный анализ данных

1. Напишите запрос, который посчитает количество вакансий в нашей базе (вакансии находятся в таблице vacancies).

In [36]:
# текст запроса
query_3_1 = f'''select count(id)
                from vacancies
'''

In [104]:
df = pd.read_sql_query(query_3_1, connection)
df

<ipython-input-104-2e12baac1c84>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_1, connection)

   count
0  49197

2. Напишите запрос, который посчитает количество работодателей (таблица employers).

In [40]:
query_3_2 = f'''select count(id)
                from employers
'''

In [41]:
df = pd.read_sql_query(query_3_2, connection)
df

<ipython-input-41-73a9d6450d46>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_2, connection)

   count
0  23501

3. Посчитате с помощью запроса количество регионов (таблица areas).

In [42]:
query_3_3 = f'''select count(id)
                from areas
'''

In [103]:
df = pd.read_sql_query(query_3_3, connection)
df

<ipython-input-103-0e918ca7d0bf>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_3, connection)

   count
0   1362

4. Посчитате с помощью запроса количество сфер деятельности в базе (таблица industries).

In [44]:
query_3_4 = f'''select count(id)
                from industries
'''

In [45]:
df = pd.read_sql_query(query_3_4, connection)
df

<ipython-input-45-e38904239d61>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_4, connection)

   count
0    294

***

In [ ]:
# выводы по предварительному анализу данных

# Юнит 4. Детальный анализ вакансий

1. Напишите запрос, который позволит узнать, сколько (cnt) вакансий в каждом регионе (area).
Отсортируйте по количеству вакансий в порядке убывания.

In [47]:
query_4_1 = f'''SELECT COUNT(vacancies.id) AS cnt, areas.name
                FROM vacancies LEFT JOIN areas
                ON vacancies.area_id = areas.id
                GROUP BY areas.name
                ORDER BY 1 DESC;
              '''

In [48]:
df = pd.read_sql_query(query_4_1, connection)
df

<ipython-input-48-159b6cda72e4>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_1, connection)

      cnt             name
0    5333           Москва
1    2851  Санкт-Петербург
2    2112            Минск
3    2006      Новосибирск
4    1892           Алматы
..    ...              ...
764     1       Тарко-Сале
765     1    Новоаннинский
766     1            Бирск
767     1           Сасово
768     1             Анна

[769 rows x 2 columns]

2. Напишите запрос, чтобы определить у какого количества вакансий заполнено хотя бы одно из двух полей с зарплатой.

In [50]:
query_4_2 = f'''SELECT salary_from, salary_to
                FROM vacancies
                WHERE (salary_from IS NOT NULL) or (salary_to IS NOT NULL)
                GROUP BY id, salary_from, salary_to;
              '''

In [51]:
df = pd.read_sql_query(query_4_2, connection)
df

<ipython-input-51-bc2660511aac>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_2, connection)

       salary_from  salary_to
0          40000.0    60000.0
1          42716.0    54921.0
2              NaN   200000.0
3              NaN   160000.0
4         150000.0        NaN
...            ...        ...
24068      80000.0    80000.0
24069      38500.0    46500.0
24070      33000.0    60000.0
24071      80000.0        NaN
24072      58000.0        NaN

[24073 rows x 2 columns]

3. Найдите средние значения для нижней и верхней границы зарплатной вилки. Округлите значения до целого.

In [56]:
query_4_3 = f'''SELECT ROUND(AVG(salary_from)), ROUND(AVG(salary_to))
                FROM vacancies;
              '''

In [57]:
df = pd.read_sql_query(query_4_3, connection)
df

<ipython-input-57-2e59bb5fdb4f>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_3, connection)

     round     round
0  71065.0  110537.0

4. Напишите запрос, который выведет количество вакансий для каждого сочетания типа рабочего графика (schedule) и типа трудоустройства (employment), используемого в вакансиях. Результат отсортируйте по убыванию количества.

In [60]:
query_4_4 = f'''SELECT count(DISTINCT name), schedule, employment
                FROM vacancies
                GROUP BY schedule, employment
                ORDER BY 1 DESC;
              '''

In [61]:
df = pd.read_sql_query(query_4_4, connection)
df

<ipython-input-61-62c3780295f9>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_4, connection)

    count          schedule           employment
0   16241       Полный день     Полная занятость
1    3574  Удаленная работа     Полная занятость
2    1063     Гибкий график     Полная занятость
3     546    Сменный график     Полная занятость
4     364       Полный день           Стажировка
5     231       Полный день  Частичная занятость
6     202  Удаленная работа  Частичная занятость
7     143     Гибкий график  Частичная занятость
8     137    Вахтовый метод     Полная занятость
9     103       Полный день     Проектная работа
10    101     Гибкий график           Стажировка
11     93  Удаленная работа     Проектная работа
12     47  Удаленная работа           Стажировка
13     29    Сменный график  Частичная занятость
14     15     Гибкий график     Проектная работа
15      6    Сменный график           Стажировка
16      2    Вахтовый метод     Проектная работа
17      1    Сменный график     Проектная работа

5. Напишите запрос, выводящий значения поля Требуемый опыт работы (experience) в порядке возрастания количества вакансий, в которых указан данный вариант опыта.

In [63]:
query_4_5 = f'''SELECT experience, count(name)
                FROM vacancies
                GROUP BY experience
                ORDER BY 2;
              '''

In [65]:
df = pd.read_sql_query(query_4_5, connection)
df

<ipython-input-65-28aeb8dfb960>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_5, connection)

           experience  count
0         Более 6 лет   1337
1           Нет опыта   7197
2       От 3 до 6 лет  14511
3  От 1 года до 3 лет  26152

***

In [2]:
Благодаря детальному анализу вакансий можно сделать вывод, что наибольшее количество вакансий охватывает города-миллионники.
Хотя средние значения для нижней и верхней границы зарплатной вилки лежат в диапазоне от 71000 руб. до 110000 руб.,
также много вакансий в которых либо отсутствует информация о заработной плате, либо указана только одна граница,
что может говорить о том, что зарплата часто является вопросом, который обусуждается после собеседования. Наиболее популярным видом трудоустройства
является "полная занятость" с различными типами рабочего графика, что свидетельствует о том, что данную профессию чаще выбирают, как основной вид
деятельности, а не как подработку. Из соотношения требуемого опыта, можно сделать вывод, что вакансий с требованием значительного опыта гораздо меньше,
что может говорит о том, что таких вакансии подразумевают управление командой молодых сотрудников.

IndentationError: unexpected indent (<ipython-input-2-5d4270c779d3>, line 2)

# Юнит 5. Анализ работодателей

1. Напишите запрос, который позволит узнать, какие работодатели находятся на первом и пятом месте по количеству вакансий.

In [67]:
query_5_1 = f'''SELECT COUNT(vacancies.id), employers.name
                FROM vacancies LEFT JOIN employers
                ON vacancies.employer_id = employers.id
                GROUP BY 2
                ORDER BY 1 DESC
                LIMIT 5;
              '''

In [68]:
df = pd.read_sql_query(query_5_1, connection)
df

<ipython-input-68-04fb89736779>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_1, connection)

   count           name
0   1933         Яндекс
1    491     Ростелеком
2    444       Тинькофф
3    428           СБЕР
4    331  Газпром нефть

2. Напишите запрос, который для каждого региона выведет количество работодателей и вакансий в нём.
Среди регионов, в которых нет вакансий, найдите тот, в котором наибольшее количество работодателей.

In [69]:
query_5_2 = f'''SELECT a.name area, COUNT(DISTINCT v.id) vacation, COUNT(DISTINCT e.id) company
                FROM areas a LEFT JOIN vacancies v
                ON a.id = v.area_id
                             LEFT JOIN employers e
                ON a.id = e.area
                WHERE v.area_id IS NULL
                GROUP BY a.name
                ORDER BY 3 DESC;
              '''

In [71]:
df = pd.read_sql_query(query_5_2, connection)
df

<ipython-input-71-be04da19801e>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_2, connection)

                               area  vacation  company
0                            Россия         0      410
1                         Казахстан         0      207
2                Московская область         0       75
3                Краснодарский край         0       19
4                          Беларусь         0       18
..                              ...       ...      ...
588                        Кувандык         0        0
589                        Куйбышев         0        0
590  Куйбышево (Ростовская область)         0        0
591                        Култаево         0        0
592                        Кульсары         0        0

[593 rows x 3 columns]

3. Для каждого работодателя посчитайте количество регионов, в которых он публикует свои вакансии. Отсортируйте результат по убыванию количества.

In [7]:
query_5_3 = f'''SELECT e.name, COUNT(DISTINCT v.area_id)
                FROM employers e LEFT JOIN vacancies v
                ON  v.employer_id = e.id
                GROUP BY e.name
                ORDER BY 2 DESC;
              '''

In [8]:
df = pd.read_sql_query(query_5_3, connection)
df

<ipython-input-8-ad7a03e90e40>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_3, connection)

                         name  count
0                      Яндекс    181
1                  Ростелеком    152
2                  Спецремонт    116
3      Поляков Денис Иванович     88
4                   ООО ЕФИН      71
...                       ...    ...
23170                  СДЕЛКА      0
23171            Alandr Group      0
23172                     СДК      0
23173      Lemon Land Lombard      0
23174                  Махина      0

[23175 rows x 2 columns]

4. Напишите запрос для подсчёта количества работодателей, у которых не указана сфера деятельности.

In [75]:
query_5_4 = f'''SELECT COUNT(DISTINCT e.id), ei.industry_id
                FROM employers e LEFT JOIN employers_industries ei
                ON e.id = ei.employer_id
                WHERE ei.industry_id IS NULL
                GROUP BY 2;
              '''

In [78]:
df = pd.read_sql_query(query_5_4, connection)
df

<ipython-input-78-2acad3d05fd6>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_4, connection)

   count industry_id
0   8419        None

5. Напишите запрос, чтобы узнать название компании, находящейся на третьем месте в алфавитном списке (по названию) компаний, у которых указано четыре сферы деятельности.

In [79]:
query_5_5 = f'''SELECT e.name, COUNT(ei.industry_id)
                FROM employers e LEFT JOIN employers_industries ei
                ON e.id = ei.employer_id
                GROUP BY 1
                HAVING COUNT(ei.industry_id) = 4
                ORDER BY 1;
              '''

In [80]:
df = pd.read_sql_query(query_5_5, connection)
df

<ipython-input-80-b4fd0715c68c>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_5, connection)

                 name  count
0        101 Интернет      4
1            21vek.by      4
2                2ГИС      4
3                  2К      4
4         4 пикселя +      4
...               ...    ...
1131            ЮРИОН      4
1132  ЮТИП Технологии      4
1133           ЯКласс      4
1134            ЯрНео      4
1135    Яшин&Партнёры      4

[1136 rows x 2 columns]

6. С помощью запроса выясните, у какого количества работодателей в качестве сферы деятельности указана Разработка программного обеспечения.

In [83]:
query_5_6 = f'''SELECT COUNT(ei.employer_id), i.name
                FROM employers_industries ei LEFT JOIN industries i
                ON ei.industry_id = i.id
                GROUP BY 2
                HAVING i.name = 'Разработка программного обеспечения';
              '''

In [82]:
df = pd.read_sql_query(query_5_6, connection)
df

<ipython-input-82-72b0d7d51819>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_6, connection)

   count                                 name
0   3553  Разработка программного обеспечения

7. Для компании «Яндекс» выведите список регионов-миллионников, в которых представлены вакансии компании, вместе с количеством вакансий в этих регионах. Также добавьте строку Total с общим количеством вакансий компании. Результат отсортируйте по возрастанию количества.

Список городов-милионников надо взять [отсюда](https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B0-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D0%B5%D1%80%D1%8B_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8).

Если возникнут трудности с этим задание посмотрите материалы модуля  PYTHON-17. Как получать данные из веб-источников и API.

In [84]:
import requests
from bs4 import BeautifulSoup

url = 'https://ru.wikipedia.org/wiki/Города-миллионеры_России'
response = requests.get(url)
page = BeautifulSoup(response.text, 'html.parser')
city = str(page.find('table', class_="standard"))
city = city.split('title="')[3:]

million_city = []
for i in city:
    million_city.append(i.split('">')[0])
print(million_city)

['Москва', 'Санкт-Петербург', 'Новосибирск', 'Екатеринбург', 'Казань', 'Красноярск', 'Нижний Новгород', 'Челябинск', 'Уфа', 'Самара', 'Ростов-на-Дону', 'Краснодар', 'Омск', 'Воронеж', 'Пермь', 'Волгоград']

In [85]:
query_5_7 = f'''
                WITH temp AS
                (SELECT a.name, COUNT(*) cnt
                FROM employers e
                      JOIN vacancies v ON e.id = v.employer_id
                      JOIN areas a ON a.id = v.area_id
                WHERE e.name = 'Яндекс' and a.name in ('Москва', 'Санкт-Петербург', 'Новосибирск', 'Екатеринбург', 'Казань', 'Красноярск', 'Нижний Новгород', 'Челябинск', 'Уфа', 'Самара', 'Ростов-на-Дону', 'Краснодар', 'Омск', 'Воронеж', 'Пермь', 'Волгоград')
                GROUP BY a.id)
                SELECT temp.name, temp.cnt
                FROM temp
                UNION ALL
                SELECT 'Total',
                       sum(temp.cnt)
                FROM temp
                ;
              '''

In [86]:
df = pd.read_sql_query(query_5_7, connection)
df

<ipython-input-86-67d00bcd1cc3>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_7, connection)

               name    cnt
0            Москва   54.0
1   Санкт-Петербург   42.0
2      Екатеринбург   39.0
3       Новосибирск   35.0
4         Волгоград   24.0
5           Воронеж   32.0
6         Краснодар   30.0
7        Красноярск   23.0
8   Нижний Новгород   36.0
9              Омск   21.0
10            Пермь   25.0
11   Ростов-на-Дону   25.0
12           Самара   26.0
13           Казань   25.0
14              Уфа   26.0
15        Челябинск   22.0
16            Total  485.0

***

In [ ]:
Анализ работодателей показал, что наибольшее количество вакансий относятся к работодателям из IT и банков.

# Юнит 6. Предметный анализ

1. Сколько вакансий имеет отношение к данным?

Считаем, что вакансия имеет отношение к данным, если в её названии содержатся слова 'data' или 'данн'.

*Подсказка: Обратите внимание, что названия вакансий могут быть написаны в любом регистре.*

In [87]:
query_6_1 = f'''SELECT id, name
                FROM vacancies
                WHERE LOWER(name) LIKE '%data%' or LOWER(name) LIKE '%данн%'
                GROUP BY 1, 2;
              '''

In [88]:
df = pd.read_sql_query(query_6_1, connection)
df

<ipython-input-88-87ca956749ae>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_1, connection)

            id                                               name
0     33368305              Аналитик данных (Департамент закупок)
1     38591002       Ведущий разработчик баз данных Oracle Pl/SQL
2     38792530                             Разработчик баз данных
3     39345694                                    Аналитик данных
4     39733919  Администратор платформы больших данных (Big Da...
...        ...                                                ...
1766  66192509                             Разработчик баз данных
1767  66193657                                       Data Analyst
1768  66195062                                       Data Analyst
1769  66195063                                       Data Analyst
1770  66195157                    Инженер системы передачи данных

[1771 rows x 2 columns]

2. Сколько есть подходящих вакансий для начинающего дата-сайентиста?
Будем считать вакансиями для дата-сайентистов такие, в названии которых есть хотя бы одно из следующих сочетаний:
* 'data scientist'
* 'data science'
* 'исследователь данных'
* 'ML' (здесь не нужно брать вакансии по HTML)
* 'machine learning'
* 'машинн%обучен%'

** В следующих заданиях мы продолжим работать с вакансиями по этому условию.*

Считаем вакансиями для специалистов уровня Junior следующие:
* в названии есть слово 'junior' *или*
* требуемый опыт — Нет опыта *или*
* тип трудоустройства — Стажировка.

In [90]:
query_6_2 = f'''SELECT count(id)
                FROM vacancies
                WHERE (name ILIKE '%data scientist%'
                   or name ILIKE '%data science%'
                   or name ILIKE '%исследователь данных%'
                   or (name ILIKE '%ML%' and name NOT ILIKE '%HTML%')
                   or name ILIKE '%machine learning'
                   or name ILIKE '%машинн%обучен%')
                   AND (name ILIKE '%junior%'
                   OR experience = 'Нет опыта'
                   OR schedule = 'Стажировка');
              '''

In [91]:
df = pd.read_sql_query(query_6_2, connection)
df

<ipython-input-91-b98f37e9e8a0>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_2, connection)

   count
0     51

3. Сколько есть вакансий для DS, в которых в качестве ключевого навыка указан SQL или postgres?

** Критерии для отнесения вакансии к DS указаны в предыдущем задании.*

In [92]:
query_6_3 = f'''select count(*) cnt
from vacancies v
where (name ilike '%data scientist%'
or name ilike '%data science%'
or name ilike '%исследователь данных%'
or (name like '%ML%' and name not ilike '%HTML%')
or name ilike '%machine learning%' or name ilike '%машинн%обучен%'
)
and
(key_skills ilike '%sql%' or key_skills ilike '%postgres%');

'''

In [93]:
df = pd.read_sql_query(query_6_3, connection)
df

<ipython-input-93-aa61b09d8160>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_3, connection)

   cnt
0  201

4. Проверьте, насколько популярен Python в требованиях работодателей к DS.Для этого вычислите количество вакансий, в которых в качестве ключевого навыка указан Python.

** Это можно сделать помощью запроса, аналогичного предыдущему.*

In [95]:
query_6_4 = f'''SELECT count(id)
                FROM vacancies
                WHERE (name ILIKE '%data scientist%'
                   or name ILIKE '%data science%'
                   or name ILIKE '%исследователь данных%'
                   or (name ILIKE '%ML%' and name NOT ILIKE '%HTML%')
                   or name ILIKE '%machine learning'
                   or name ILIKE '%машинн%обучен%')
                   AND (key_skills ILIKE '%python%')
                   ;
              '''

In [96]:
df = pd.read_sql_query(query_6_4, connection)
df

<ipython-input-96-16cb88c0e374>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_4, connection)

   count
0    341

5. Сколько ключевых навыков в среднем указывают в вакансиях для DS?
Ответ округлите до двух знаков после точки-разделителя.

In [98]:
query_6_5 = f'''SELECT round(avg(length(key_skills)-length(replace(key_skills, CHR(9), ''))+1), 2) cnt_ks
               FROM vacancies v
               WHERE (name ilike '%data scientist%'
               or name ilike '%data science%'
               or name ilike '%исследователь данных%'
               or (name like '%ML%' and name not ilike '%HTML%')
               or name ilike '%machine learning%' or name ilike '%машинн%обучен%');
              '''

In [99]:
df = pd.read_sql_query(query_6_5, connection)
df

<ipython-input-99-eda0e64a627b>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_5, connection)

   cnt_ks
0    6.41

6. Напишите запрос, позволяющий вычислить, какую зарплату для DS в **среднем** указывают для каждого типа требуемого опыта (уникальное значение из поля *experience*).

При решении задачи примите во внимание следующее:
1. Рассматриваем только вакансии, у которых заполнено хотя бы одно из двух полей с зарплатой.
2. Если заполнены оба поля с зарплатой, то считаем зарплату по каждой вакансии как сумму двух полей, делённую на 2. Если заполнено только одно из полей, то его и считаем зарплатой по вакансии.
3. Если в расчётах участвует null, в результате он тоже даст null (посмотрите, что возвращает запрос select 1 + null). Чтобы избежать этой ситуацию, мы воспользуемся функцией [coalesce](https://postgrespro.ru/docs/postgresql/9.5/functions-conditional#functions-coalesce-nvl-ifnull), которая заменит null на значение, которое мы передадим. Например, посмотрите, что возвращает запрос `select 1 + coalesce(null, 0)`

Выясните, на какую зарплату в среднем может рассчитывать дата-сайентист с опытом работы от 3 до 6 лет. Результат округлите до целого числа.

In [101]:
query_6_6 = f'''SELECT experience,
                ROUND(AVG(coalesce((v.salary_from + v.salary_to) / 2, v.salary_from, v.salary_to)), 0)
                FROM vacancies v
                WHERE (salary_from IS NOT NULL OR salary_to IS NOT NULL)
                AND (name ILIKE '%data scientist%'
                OR name ILIKE '%data science%'
                OR name ILIKE '%исследователь данных%'
                OR (name LIKE '%ML%' AND name NOT ILIKE '%HTML%')
                OR name ILIKE '%machine learning%'
                OR name ILIKE '%машинн%обучен%')
                GROUP BY experience
                ORDER BY experience;
              '''

In [102]:
df = pd.read_sql_query(query_6_6, connection)
df

<ipython-input-102-1a9414fb0607>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_6, connection)

           experience     round
0           Нет опыта   74643.0
1  От 1 года до 3 лет  139675.0
2       От 3 до 6 лет  243115.0

***

In [ ]:
Предметный анализ данных показал, что вакансий для специалиста без опыта значительно меньше относительно общего количества вакансий.
Но и зарплата для специалиста с опытом 1-3 года отличается от специалиста без опыта почти в 2 раза. Согласно данным одними из ключевых навыков
для специалиста работающего с данными являются: python, sql, postgres.

# Общий вывод по проекту

In [ ]:
Основной вывод по данному проекту заключается в том, что наибольшее количество вакансий и наибольшая заработная плата предлагается специалистам
с опытом 1-3 года.

In [ ]:
connection.close()